---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-vscode
description: Install vscode through ansible
tags:
  - ansible
  - ansible-role
  - vscode
github:
  has_issues: true
  has_projects: false
  has_wiki: false
